version: '3.8'
services:
  db:
    image: mysql:8.0
    container_name: mysql-product
    environment:
      MYSQL_ROOT_PASSWORD: sook6538
      MYSQL_DATABASE: spring_proj_product
    ports:
      - "3307:3306"
    healthcheck:
      test: ["CMD-SHELL", "mysqladmin ping -h localhost -u root -psook6538"]
      interval: 5s
      retries: 10

  redis:
    image: redis:latest
    container_name: redis-container-product
    ports:
      - "6380:6379"
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 30s
      timeout: 10s
      retries: 5